### PR TITLE
Fixed issue #7

### PR DESCRIPTION
**Pull request by sarveshdakhore**
Fixed issue #7 

image

### CODE REVIEW

**Comment by TejasGhatte** [comment]
gg, also handle cancellation gracefully when populate directory function is running, right now it works fast but later it could take longer. So user can cancel that as well.

**Comment by sarveshdakhore** [comment]
so should i edit it or it will get accepted


> gg, also handle cancellation gracefully when populate directory function is running, right now it works fast but later it could take longer. So user can cancel that as well.

**Comment by TejasGhatte** [comment]
edit this, then ill merge

**Comment by sarveshdakhore** [comment]
> edit this, then ill merge

done, its working fine, if cancelled in mid it will clean the created dir so for next time no err will occur

image

**Pull request merged**
