### PR TITLE
Fixed issue #5

### PR DESCRIPTION
**Pull request by sarveshdakhore**
Fixed issue #5 

used goImports
go install golang.org/x/tools/cmd/goimports@latest
set the path

image

image

### CODE REVIEW

**Comment by TejasGhatte** [comment]
this is a pretty long approach, you can manage entire project folder in one function, no need of running command on each file.

**Comment by sarveshdakhore** [comment]
> this is a pretty long approach, you can manage entire project folder in one function, no need of running command on each file.

I changed the runGoImports function so that it now runs on the entire project directory instead of on individual files.

**Comment by TejasGhatte** [comment]
but, still its looping on each file to download the imports, no need for that. There is a better approach

**Comment by TejasGhatte** [comment]
still not optimal :| use inbuilt go commands like go mod ...... so no need to list and get each package.

**Comment by sarveshdakhore** [comment]
> but, still its looping on each file to download the imports, no need for that. There is a better approach

I fixed this
replaced the extract function and now using - go list to get all imports at once

> still not optimal :| use inbuilt go commands like go mod ...... so no need to list and get each package.

now using go mod vendor, and removed the useless context checks and combined the functions runGoModTidy and runGoModVendor

**Comment by TejasGhatte** [comment]
working? can you tell me the flow of this, i havent used go mod vendor.

**Pull request merged**
